development:
  adapter: postgresql
  encoding: unicode
  database: ius_library_development
  pool: 5
  username: rialda
  password: rialda

test:
  adapter: postgresql
  encoding: unicode
  database: ius_library_development
  pool: 5
  username: rialda
  password: rialda
